server:
  port: 8081

spring:
  application:
    name: cv-ingestion-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.value.default.type: com.aayadi.contracts.events.CvSubmittedEvent
      spring.json.add.type.headers: false

app:
  topics:
    cvSubmitted: cv-submitted-events
